import { createPortal } from 'react-dom';
import { useState } from 'react';
import { ArrowLeft } from 'lucide-react';
import SquadDiscovery, { players } from './SquadDiscovery';
import SquadEditor, { emptyIntent } from './SquadEditor';
import SettingsMenu from './SettingsMenu';
import './SquadPage.css';
const key='gb-squad-workspace-v1';
const initial={connections:[],intents:{},interests:[],invitations:[],ready:false,orders:[],feedback:{}};
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(key)||'{}')};}catch{return initial;}}
export default function SquadPage({chinese, scenarioHost}){
 const t=(en,zh)=>chinese?zh:en,l=chinese?1:0;
 const [deckKey,setDeckKey]=useState(0);
 const [data,setData]=useState(load),[screen,setScreen]=useState('discover'),[game,setGame]=useState('wzry'),[filters,setFilters]=useState({role:'',v10:false}),[target,setTarget]=useState(players[0]),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState(false),[time,setTime]=useState('20:00–22:00'),[selected,setSelected]=useState(null),[scenario,setScenario]=useState(false),[results,setResults]=useState(['win','loss','win']);
 const gameName=game==='wzry'?t('Honor of Kings','王者荣耀'):t('Golden Spatula','金铲铲之战');
 function update(patch){const next={...data,...patch};try{localStorage.setItem(key,JSON.stringify(next));setData(next);return true;}catch{setNotice(t('Could not save. Please retry.','保存失败，请重试。'));return false;}}
 const go=page=>{setScreen(page);setNotice('');setConfirm(false);};
 const title={discover:t('Squad','组队'),editor:t('My card','我的卡片'),filters:t('Filters','筛选'),profile:t('Player profile','玩家画像'),rules:t('Skin sharing','皮肤共享'),messages:t('Messages','消息'),teammates:t('Teammates','我的搭子'),invite:t('Invite to play','邀请一起玩'),invitation:t('Invitation','约玩邀请'),handoff:t('Ready to play','准备开局'),feedback:t('How was it?','游玩反馈'),services:t('Play together service','一起上分服务'),order:t('Review order','确认订单'),orders:t('My orders','我的订单'),settlement:t('Review results','核对结果'),provider:t('Offer a service','发布服务')};
 const invitations=data.invitations.filter(i=>i.game===game),current=data.invitations.find(i=>i.id===selected),order=data.orders.find(i=>i.id===selected);
 const teammateRows=game==='wzry'?[{id:'che-v1',name:players[0].name,ready:true,status:t('Online · ready to play','在线 · 现在可开局'),history:t('Played yesterday · both confirmed','昨天一起玩过 · 双方确认')},{id:'nan',name:['Nan','小南'],ready:false,status:t('Online · in game','在线 · 游戏中'),history:t('Last invitation expired','上次邀请已过期')},{id:'bei',name:['Bei','北辰'],ready:false,status:t('Offline · readiness unknown','离线 · 可约状态未知'),history:t('Matched · not played together yet','已互选 · 还未一起玩')}]:[{id:'spatula',name:['Lin','小林'],ready:true,status:t('Online · ready to play','在线 · 现在可开局'),history:t('Matched · not played together yet','已互选 · 还未一起玩')}];
 function invite(ids){if(!time.trim())return;const created=ids.map(id=>({id:crypto.randomUUID(),player:id,game,time,status:'pending',incoming:false,created:Date.now()}));if(update({invitations:[...created,...data.invitations]})){setSelected(created[0].id);go('invitation');}}
 function invitationState(state){if(!current)return;if(update({invitations:data.invitations.map(i=>i.id===current.id?{...i,status:state}:i)})){if(state==='accepted')go('handoff');else setNotice(t('Invitation updated.','邀请状态已更新。'));}}
 const status=s=>({pending:t('Waiting for response','等待回应'),accepted:t('Accepted','已接受'),declined:t('Declined','已婉拒'),canceled:t('Canceled','已取消'),expired:t('Expired','已过期'),review:t('Results pending review','结果待核对'),complete:t('Results confirmed · refund pending','结果已确认 · 退款待处理'),disputed:t('Needs review','存在分歧'),paid:t('Payment pending','等待付款')}[s]||s);
 const row=(label,action,sub)=> <button className="ac-row" onClick={action}><span>{label}{sub&&<small>{sub}</small>}</span><span aria-hidden="true">›</span></button>;
 return <section className="bp-page ac-page sq-workspace">
  <header className="bp-header">{screen!=='discover'&&<button className="bp-icon-button" aria-label={t('Back','返回')} onClick={()=>go('discover')}><ArrowLeft/></button>}<h1>{title[screen]}</h1></header>
  {<div hidden={screen!=='discover'}>
   <div className="sq-navigation"><SettingsMenu label={t('Game','游戏')} value={game} options={[["wzry",t('Honor of Kings','王者荣耀')],["jcc",t('Golden Spatula','金铲铲')]]} onChange={v=>{setGame(v);setFilters({role:'',v10:false});}}/><button className="bp-text-button" onClick={()=>go('filters')}>{t('Filters','筛选')}{(filters.role||filters.v10)?' •':''}</button><button className="bp-text-button" onClick={()=>go('editor')}>{t('My card','我的卡片')}</button></div>
   <SquadDiscovery key={`${game}-${deckKey}`} chinese={chinese} game={game} filters={filters} onProfile={p=>{setTarget(p);go('profile');}} onRules={()=>go('rules')} onInterest={id=>update({interests:[...new Set([...data.interests,id])]})}/>
   <div className="ac-group">{row(t('Teammates & messages','搭子与消息'),()=>go('messages'))}{row(t('Play together services','一起上分服务'),()=>go('services'))}</div>
  </div>}
  {screen==='filters'&&<div className="sq-form"><div className="ac-group"><div className="ac-row"><span>{t('Position','位置')}</span><SettingsMenu label={t('Position','位置')} value={filters.role} options={[["",t('Any','不限')],["Support",t('Support','辅助')],["Jungle",t('Jungle','打野')],["Clash lane",t('Clash lane','对抗路')]]} onChange={role=>setFilters({...filters,role})}/></div><div className="ac-row"><span>{t('V10 sharing','V10 共享')}</span><button className="ac-switch" role="switch" aria-label="V10" aria-checked={filters.v10} onClick={()=>setFilters({...filters,v10:!filters.v10})}><span/></button></div></div><p>{t('Temporary filters do not change your published needs. Specific skins and available uses still require confirmation.','临时筛选不会修改你的公开需要，指定皮肤与可用次数仍需确认。')}</p><button className="bp-primary" onClick={()=>go('discover')}>{t('Show players','查看玩家')}</button><button className="bp-text-button" onClick={()=>setFilters({role:'',v10:false})}>{t('Reset filters','重置筛选')}</button></div>}
  {screen==='editor'&&<SquadEditor chinese={chinese} initial={data.intents[game]||emptyIntent} onCancel={()=>go('discover')} onSave={intent=>{if(update({intents:{...data.intents,[game]:intent}})){go('discover');setNotice(t('Your demo card has been updated.','演示卡片已更新。'));}}}/>}
  {screen==='profile'&&<div className="sq-form"><div className="sq-person"><div className="sq-avatar">{target.name[l][0]}</div><h2>{target.name[l]}</h2></div><p>{gameName} · {target.role[l]}</p><div className="sq-card"><h3>{target.style[l]}</h3><p>{target.body[l]}</p><div className="sq-tags">{target.tags.map(tag=><span key={tag[0]}>{tag[l]}</span>)}</div></div><div className="sq-card"><h3>{t('Recent performance','近期表现')}</h3><p>{target.id==='che-v1'?t('Support · 50 games · 68% win rate','辅助位 · 近50局 · 胜率68%'):t('Not shared','未公开')}</p><small>{t('Prototype data, not verified records','原型示例数据，非核验记录')}</small></div><div className="sq-card"><h3>{t('Hero pool','常用英雄')}</h3><p>{target.id==='che-v1'?t('Zhang Fei · Niu Mo','张飞 · 牛魔'):t('Not shared','未公开')}</p></div>{target.id==='che-v1'&&row('V10',()=>go('rules'))}<small>{t('Only public profile content is shown. Private memories are not included.','仅展示公开画像，不包含私人记忆。')}</small><button className="bp-primary" onClick={()=>go('discover')}>{t('Back to player card','返回玩家卡片')}</button></div>}
  {screen==='rules'&&<div className="sq-form"><h2>{t('Team skin sharing','组队皮肤共享')}</h2><p>{t('V10 is a profile claim. Willingness to share is a separate offer.','V10 是画像信息，本次愿意共享是独立的提供条目。')}</p><div className="sq-card"><p>{t('Confirm the same team, selected hero, skin ownership and the recipient’s remaining allowance.','需确认同队、所选英雄、指定皮肤持有及体验方剩余次数。')}</p><small>{t('Remaining uses: unknown. No uses are consumed by swiping or accepting an invitation.','剩余次数：未知。滑动或接受邀请不会扣减次数。')}</small></div><button className="bp-primary" onClick={()=>go('discover')}>{t('Back to discovery','返回发现')}</button></div>}
  {screen==='messages'&&<><div className="ac-group">{row(t('My teammates','我的搭子'),()=>go('teammates'))}{row(t('My orders','我的订单'),()=>go('orders'))}</div><h3>{t('Interested in playing','想一起玩')}</h3>{data.interests.length?data.interests.map(id=><div className="sq-card" key={id}><h2>{players.find(p=>p.id===id)?.name[l]}</h2><small>{data.connections.includes(id)?t('Mutual interest · you can arrange a game','已互选 · 可以约玩'):t('Your interest · awaiting their response','单方兴趣 · 等待回应')}</small>{data.connections.includes(id)&&<button className="bp-text-button" onClick={()=>{setTarget(players.find(p=>p.id===id));go('invite');}}>{t('Invite to play','邀请一起玩')}</button>}</div>):<p>{t('No new interests yet','暂无新的意向')}</p>}<div className="sq-card"><h3>{t('Mutual matches','互选消息')}</h3><p>{t('Che is in your example teammate history. Matching and being ready to play are separate.','阿澈已在示例搭子历史中。互选与当前可开局状态互相独立。')}</p><button className="bp-text-button" onClick={()=>go('teammates')}>{t('View teammate history','查看搭子历史')}</button></div><h3>{t('Invitations','约玩邀请')}</h3>{invitations.length?invitations.map(i=>row(`${teammateRows.find(p=>p.id===i.player)?.name[l]||i.player} · ${status(i.status)}`,()=>{setSelected(i.id);go('invitation');},i.time)):<p>{t('No invitations yet','暂无邀请')}</p>}</>}
  {screen==='teammates'&&<><div className="sq-navigation"><SettingsMenu label={t('Game','游戏')} value={game} options={[["wzry",t('Honor of Kings','王者荣耀')],["jcc",t('Golden Spatula','金铲铲')]]} onChange={setGame}/><button className="bp-text-button" onClick={()=>update({ready:!data.ready})}>{data.ready?t('I’m ready','我现在可开局'):t('Set ready to play','设置可开局')}</button></div><small>{t('Example mutual matches and history','示例互选与历史记录')}</small>{teammateRows.map(p=><article className="sq-card" key={p.id}><h2>{p.name[l]}</h2>{p.id==='che-v1'&&<button className="bp-text-button" onClick={()=>{setTarget(players[0]);go('profile');}}>{t('View profile','查看画像')}</button>}<p>{p.status}</p><small>{p.history}</small><button className="bp-text-button" onClick={()=>{setTarget({...p,role:['','']});go('invite');}}>{t('Invite','邀请')}</button></article>)}<button className="bp-primary" onClick={()=>{setTarget({id:'all',name:[t('All ready teammates','全部可开局搭子'),t('All ready teammates','全部可开局搭子')]});go('invite');}}>{t('Invite all ready teammates','邀请全部可开局搭子')} · {teammateRows.filter(p=>p.ready).length}</button></>}
  {screen==='invite'&&<div className="sq-form"><h2>{target.name[l]}</h2><p>{gameName} · {t('Ranked · one open spot','排位 · 还差1人')}</p><label>{t('Time','时间')}<input value={time} onChange={e=>setTime(e.target.value)}/></label><p>{t('An invitation asks for this session only. It does not mean they have accepted.','邀请只针对本次约玩，不代表对方已经接受。')}</p><button className="bp-primary" disabled={!time.trim()} onClick={()=>invite(target.id==='all'?teammateRows.filter(p=>p.ready).map(p=>p.id):[target.id])}>{t('Send invitation','发送邀请')}</button></div>}
  {screen==='invitation'&&current&&<div className="sq-form"><h2>{status(current.status)}</h2><p>{gameName} · {current.time} · {t('Ranked','排位')}</p>{current.status==='pending'&&current.incoming?<><label><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>{t('I can start a new game at this time','我可以在该时段开新局')}</label><button className="bp-primary" disabled={!confirm} onClick={()=>invitationState('accepted')}>{t('Accept invitation','接受邀请')}</button><button className="bp-text-button" onClick={()=>invitationState('declined')}>{t('Not this time','这次不了')}</button></>:current.status==='pending'?<button className="bp-text-button" onClick={()=>invitationState('canceled')}>{t('Cancel invitation','取消邀请')}</button>:current.status==='accepted'?<button className="bp-primary" onClick={()=>go('handoff')}>{t('Game handoff','进入游戏前')}</button>:<button className="bp-primary" onClick={()=>go('teammates')}>{t('Find another time','再约时间')}</button>}</div>}
  {screen==='handoff'&&current?.status==='accepted'&&<div className="sq-form"><h2>{t('Your invitation is accepted','本次邀请已接受')}</h2><p>{gameName} · {current.time}</p><p>{game==='wzry'?t('Copy the demo game ID, then invite your teammate inside the game.','复制演示游戏 ID，在游戏中邀请队友。'):t('Add your teammate by game ID inside Golden Spatula.','在金铲铲中通过游戏 ID 添加好友。')}</p><div className="sq-card">GB-DEMO-{current.player}<button className="bp-text-button" onClick={async()=>{try{await navigator.clipboard.writeText(`GB-DEMO-${current.player}`);setNotice(t('Copied demo ID','已复制演示 ID'));}catch{setNotice(t('Copy unavailable. Select the ID manually.','无法复制，请手动选择 ID。'));}}}>{t('Copy ID','复制 ID')}</button></div><small>{t('Demo handoff. Accepting does not mean you are in the same game team.','演示交接信息。接受邀请不代表已进入同一游戏队伍。')}</small><button className="bp-primary" onClick={()=>go('feedback')}>{t('After playing','游玩后反馈')}</button></div>}
  {screen==='feedback'&&<div className="sq-form"><h2>{t('Did you play together?','你们一起玩了吗？')}</h2>{[['yes','Yes','玩过了'],['no','Not yet','还没有'],['skip','Skip','跳过']].map(([v,en,zh])=><button className="bp-primary" key={v} onClick={()=>{if(update({feedback:{...data.feedback,[selected]:v}})){go('messages');setNotice(t('Saved as your report, not verified game history.','已保存为你的自报，非核验游戏记录。'));}}}>{t(en,zh)}</button>)}</div>}
  {['services','order','orders','settlement','provider'].includes(screen)&&<small>{t('Service prototype · no real payments or orders','服务原型 · 不产生真实订单或支付')}</small>}
  {screen==='services'&&<div className="sq-form"><h2>{t('Che · Support','阿澈 · 辅助')}</h2><div className="sq-card"><h3>{t('¥10 per win · ¥0 per loss','胜局 ¥10 · 败局 ¥0')}</h3><p>{t('3 games · maximum ¥30. You play together.','共3局 · 最高 ¥30。本人参与组队。')}</p></div><p>{t('Support, voice communication and coordinated play. Mode, account scope and time must be agreed. Invalid games are not charged.','辅助、开麦沟通与认真配合。需确认模式、账号范围与时间。无效局不收费。')}</p><button className="bp-primary" onClick={()=>go('order')}>{t('Choose this plan','选择这份方案')}</button><button className="bp-text-button" onClick={()=>go('provider')}>{t('Offer a service','发布服务')}</button><button className="bp-text-button" onClick={()=>go('orders')}>{t('View orders','查看订单')}</button></div>}
  {screen==='order'&&<div className="sq-form"><h2>{t('Maximum ¥30','最高 ¥30')}</h2><p>{t('3 games. Win ¥10 / loss ¥0 / invalid ¥0. Two wins and one loss cost ¥20; the remaining ¥10 is refundable.','3局。胜 ¥10 / 败 ¥0 / 无效 ¥0。两胜一负为 ¥20，余款 ¥10 可退。')}</p><p>{t('Players and prices are locked for this plan. Unplayed games can be canceled; completed games follow these terms.','本方案固定参与者与价格。未开局可取消，已完成对局按约定处理。')}</p><label><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>{t('I understand this example plan','我已了解示例方案')}</label><button className="bp-primary" disabled={!confirm} onClick={()=>{const id=crypto.randomUUID();if(update({orders:[...data.orders,{id,status:'paid',results:[],game}]})){setSelected(id);go('orders');}}}>{t('Create demo order','创建演示订单')}</button></div>}
  {screen==='orders'&&<div className="sq-form">{data.orders.length?data.orders.map(o=><div className="sq-card" key={o.id}><h3>{t('Che · 3 games · up to ¥30','阿澈 · 3局 · 最高 ¥30')}</h3><p>{status(o.status)}</p>{o.status==='paid'&&<small>{t('Awaiting a payment/service event. No money has been moved.','等待支付/服务事件，未发生资金转移。')}</small>}<button className="bp-text-button" onClick={()=>{setSelected(o.id);setResults(o.results.length?o.results:['win','loss','win']);go('settlement');}}>{t('Preview result review','预览结果核对')}</button>{o.status==='paid'&&<button className="bp-text-button" onClick={()=>update({orders:data.orders.map(v=>v.id===o.id?{...v,status:'canceled'}:v)})}>{t('Cancel','取消')}</button>}</div>):<p>{t('No orders yet','暂无订单')}</p>}</div>}
  {screen==='settlement'&&order&&<div className="sq-form"><small>{t('Illustrative results for reviewing the settlement flow','用于核对结算流程的示例结果')}</small>{results.map((r,i)=><div className="ac-row" key={i}><span>{t('Game','第')}{i+1}{chinese?'局':''}</span><SettingsMenu label={`${t('Result','结果')} ${i+1}`} value={r} options={[["win",t('Win · ¥10','胜 · ¥10')],["loss",t('Loss · ¥0','败 · ¥0')],["invalid",t('Invalid · ¥0','无效 · ¥0')],["unknown",t('Unknown','待确认')]]} onChange={v=>setResults(rs=>rs.map((x,n)=>n===i?v:x))}/></div>)}<h2>{t('Total','合计')} ¥{results.filter(r=>r==='win').length*10}</h2><p>{t('Potential refund','待退金额')} ¥{30-results.filter(r=>r==='win').length*10}</p><button className="bp-primary" disabled={results.includes('unknown')||!['review','disputed'].includes(order.status)} onClick={()=>{update({orders:data.orders.map(o=>o.id===selected?{...o,status:'complete',results}:o)});go('orders');}}>{t('Confirm demo results','确认演示结果')}</button><button className="bp-text-button" disabled={!['review','disputed'].includes(order.status)} onClick={()=>{update({orders:data.orders.map(o=>o.id===selected?{...o,status:'disputed',results}:o)});go('orders');}}>{t('Raise a discrepancy','结果有分歧')}</button><small>{t('No payment or refund is executed by this preview.','此预览不会执行扣款或退款。')}</small></div>}
  {screen==='provider'&&<form className="sq-form" onSubmit={e=>{e.preventDefault();setNotice(t('Service draft saved locally for review.','服务草稿已在本地保存供预览。'));update({serviceDraft:time});}}><label>{t('Your service and available hours','服务内容与可接单时段')}<textarea required value={time} onChange={e=>setTime(e.target.value)}/></label><p>{t('Example pricing: ¥10 per win, ¥0 per loss, 3 games, cap ¥30.','示例计价：胜 ¥10、败 ¥0、3局、封顶 ¥30。')}</p><button className="bp-primary">{t('Save service draft','保存服务草稿')}</button></form>}
  {notice&&<p className="sq-notice" role="status">{notice}</p>}
  {scenarioHost && createPortal(<div className="sq-scenario-panel"><details className="sq-scenarios" open={scenario} onToggle={e=>setScenario(e.currentTarget.open)}><summary>{t('Prototype scenarios','原型演示场景')}</summary><button className="bp-text-button" onClick={()=>{localStorage.removeItem('gb-squad-discovery-demo-v1');setDeckKey(k=>k+1);go('discover');}}>{t('Replay discovery cards','重新演示发现卡片')}</button><button className="bp-text-button" onClick={()=>{const id=crypto.randomUUID();update({invitations:[{id,game,player:game==='wzry'?'che-v1':'spatula',incoming:true,time:'20:00–22:00',status:'pending'},...data.invitations]});setSelected(id);go('invitation');}}>{t('Load incoming invitation','载入收到邀请场景')}</button>{current?.status==='pending'&&!current.incoming&&<><button className="bp-text-button" onClick={()=>invitationState('accepted')}>{t('Recipient accepts (example)','对方接受（示例）')}</button><button className="bp-text-button" onClick={()=>invitationState('expired')}>{t('Invitation expires (example)','邀请过期（示例）')}</button></>}{data.interests.some(id=>!data.connections.includes(id))&&<button className="bp-text-button" onClick={()=>{update({connections:[...new Set([...data.connections,...data.interests])]});go('messages');}}>{t('Reciprocal interest arrives (example)','收到回赞（示例）')}</button>}{order?.status==='paid'&&<button className="bp-text-button" onClick={()=>update({orders:data.orders.map(o=>o.id===order.id?{...o,status:'review'}:o)})}>{t('Load paid, completed-games scenario','载入已支付且对局完成场景')}</button>}<button className="bp-text-button" onClick={()=>go('teammates')}>{t('Open example mutual matches','查看示例互选搭子')}</button></details></div>, scenarioHost)}
 </section>;
}
