import { useState } from 'react';
import SettingsMenu from './SettingsMenu';

const templates=[['role','Position / play style','位置与玩法'],['voice','Voice communication','语音沟通'],['pick','Discuss picks','选人前沟通'],['review','Review after playing','打完交流思路'],['skin','Specific skin','指定皮肤'],['benefit','Team skin sharing','组队皮肤共享'],['metric','Win-rate requirement','胜率要求'],['reward','Compensation','回报'],['custom','Custom','自定义']];
export const emptyIntent={mode:'ranked',time:'20:00–22:00',goal:'',items:[]};
export default function SquadEditor({chinese,initial,onSave,onCancel}){
 const t=(en,zh)=>chinese?zh:en;
 const [draft,setDraft]=useState(()=>structuredClone(initial||emptyIntent)),[item,setItem]=useState(null),[preview,setPreview]=useState(false),[error,setError]=useState(''),[removed,setRemoved]=useState(null),[memory,setMemory]=useState(false),[selected,setSelected]=useState([]);
 const update=(key,value)=>setDraft(d=>({...d,[key]:value}));
 const move=(id,dir)=>setDraft(d=>{const i=d.items.findIndex(v=>v.id===id),same=d.items.filter(v=>v.direction===d.items[i].direction),j=same.findIndex(v=>v.id===id)+dir;if(j<0||j>=same.length)return d;const list=[...d.items],other=list.findIndex(v=>v.id===same[j].id);[list[i],list[other]]=[list[other],list[i]];return {...d,items:list};});
 function validate(){const active=draft.items.filter(i=>!i.paused);if(!draft.time.trim())return t('Add a time window.','请填写可玩时段。');if(active.some(i=>i.kind==='voice'&&i.value==='on')&&active.some(i=>i.kind==='voice'&&i.value==='off'))return t('Resolve the conflicting voice preferences before publishing.','请先解决开麦与不开麦的冲突。');return '';}
 function saveItem(e){e.preventDefault();const next={...item,text:item.text?.trim()||'',id:item.id||crypto.randomUUID()};if(draft.items.some(i=>i.id!==next.id&&i.direction===next.direction&&i.kind===next.kind&&i.text===next.text&&i.value===next.value)){setError(t('This item already exists.','该条目已存在。'));return;}update('items',draft.items.some(i=>i.id===next.id)?draft.items.map(i=>i.id===next.id?next:i):[...draft.items,next]);setItem(null);setError('');}
 const label=i=>i.kind==='voice'?(i.value==='on'?t('Voice on','开麦沟通'):t('Voice off','不开麦')):i.text||t(...templates.find(v=>v[0]===i.kind).slice(1));
 if(item)return <form className="sq-form" onSubmit={saveItem}>
  <h2>{item.direction==='need'?t('I need','我需要'):t('I offer','我愿意提供')}</h2>
  <div className="ac-group"><div className="ac-row"><span>{t('Template','模板')}</span><SettingsMenu label={t('Template','模板')} value={item.kind} options={templates.filter(v=>item.direction==='need'||v[0]!=='metric').map(v=>[v[0],t(v[1],v[2])])} onChange={kind=>setItem({...item,kind,text:'',value:'on'})}/></div></div>
  {item.kind==='voice'?<div className="ac-row"><span>{t('Communication','沟通方式')}</span><SettingsMenu label={t('Communication','沟通方式')} value={item.value} options={[["on",t('Voice on','开麦')],["off",t('Voice off','不开麦')]]} onChange={value=>setItem({...item,value})}/></div>:<label>{t('Details','具体内容')}<input required maxLength={120} value={item.text} onChange={e=>setItem({...item,text:e.target.value})} placeholder={item.kind==='skin'?t('Hero · skin name','英雄 · 皮肤名称'):item.kind==='metric'?t('e.g. support, last 50 games ≥ 60%','例如：辅助位近50局胜率 ≥ 60%'):t('Be specific about what you need or offer','写清楚你需要或愿意提供什么')}/></label>}
  {item.direction==='need'&&<div className="ac-row"><span>{t('Must have','必须满足')}</span><button type="button" className="ac-switch" role="switch" aria-label={t('Must have','必须满足')} aria-checked={item.must} onClick={()=>setItem({...item,must:!item.must})}><span/></button></div>}
  <div className="ac-row"><span>{t('Visibility','可见范围')}</span><SettingsMenu label={t('Visibility','可见范围')} value={item.visibility} options={[["public",t('Public','公开')],["match",t('Matching only','仅用于匹配')],["private",t('Private draft','私密草稿')]]} onChange={visibility=>setItem({...item,visibility})}/></div>
  <small>{t('Manual entry · not verified. Required conditions are separate from ordering.','本人填写 · 未核验。必须满足与排序互相独立。')}</small>
  {error&&<p role="alert">{error}</p>}
  <button className="bp-primary">{t('Save item','保存条目')}</button><button type="button" className="bp-text-button" onClick={()=>{setItem(null);setError('');}}>{t('Cancel','取消')}</button>
 </form>;
 return <div className="sq-form">
  <h2>{preview?t('Public card preview','公开卡片预览'):t('This time, I want to play…','这次想玩')}</h2>
  {!preview&&<><small>{t('Draft · changes are not published yet','草稿 · 尚未更新公开卡片')}</small><label>{t('Goal','目标')}<input value={draft.goal} onChange={e=>update('goal',e.target.value)} placeholder={t('Rank up, practice, or relax','认真上分、练习或轻松玩')}/></label><label>{t('Time window','可玩时段')}<input required value={draft.time} onChange={e=>update('time',e.target.value)}/></label><div className="ac-row"><span>{t('Mode','模式')}</span><SettingsMenu label={t('Mode','模式')} value={draft.mode} options={[["ranked",t('Ranked','排位')],["casual",t('Casual','匹配')]]} onChange={v=>update('mode',v)}/></div></>}
  {preview&&<p>{draft.goal} · {draft.time}</p>}
  {['need','offer'].map(direction=><section key={direction}><div className="sq-row"><h3>{direction==='need'?t('I need','我需要'):t('I offer','我愿意提供')}</h3>{!preview&&<button className="bp-text-button" disabled={draft.items.filter(i=>i.direction===direction).length>=20} onClick={()=>setItem({direction,kind:'role',text:'',must:false,visibility:'public',value:'on',paused:false})}>{t('+ Add','＋添加')}</button>}</div>
  {draft.items.filter(i=>i.direction===direction&&(!preview||(!i.paused&&i.visibility==='public'))).map((i,index,array)=><article className="sq-card" key={i.id}><small>{index+1} · {i.must?t('Required','必须满足'):direction==='need'?t('Preferred','优先满足'):t('Willing to offer','本人愿意提供')}{i.paused?' · '+t('Paused','已暂停'):''}</small><p>{label(i)}</p>{!preview&&<><small>{i.visibility==='public'?t('Public','公开'):t('Not on public card','不在公开卡片显示')}</small><div className="sq-tools"><button onClick={()=>setItem({...i})}>{t('Edit','编辑')}</button><button disabled={index===0} aria-label={t('Move up','上移')} onClick={()=>move(i.id,-1)}>↑</button><button disabled={index===array.length-1} aria-label={t('Move down','下移')} onClick={()=>move(i.id,1)}>↓</button><button onClick={()=>update('items',draft.items.map(v=>v.id===i.id?{...v,paused:!v.paused}:v))}>{i.paused?t('Resume','恢复'):t('Pause','暂停')}</button><button onClick={()=>{setRemoved(i);update('items',draft.items.filter(v=>v.id!==i.id));}}>{t('Delete','删除')}</button></div></>}</article>)}
  {!draft.items.some(i=>i.direction===direction&&(!preview||(!i.paused&&i.visibility==='public')))&&<small>{t('Nothing shared yet','尚未填写')}</small>}</section>)}
  {removed&&!preview&&<button className="bp-text-button" onClick={()=>{update('items',[...draft.items,removed]);setRemoved(null);}}>{t('Undo deletion','撤销删除')}</button>}
  {!preview&&<><button className="bp-text-button" onClick={()=>setMemory(!memory)}>{t('Suggestions from Memory','从 Memory 整理')}</button>{memory&&<div className="sq-card"><small>{t('Example suggestions · select what to add. Nothing is shared automatically.','示例建议 · 仅添加你勾选的条目，不会自动公开。')}</small>{[t('Discuss picks before playing','选人前沟通'),t('Review the match together','打完交流思路')].map((text,i)=><label key={text}><input type="checkbox" checked={selected.includes(i)} onChange={()=>setSelected(s=>s.includes(i)?s.filter(v=>v!==i):[...s,i])}/>{text}</label>)}<button className="bp-text-button" disabled={!selected.length} onClick={()=>{update('items',[...draft.items,...selected.map(i=>({id:crypto.randomUUID(),direction:'need',kind:i?'review':'pick',text:i?t('Review the match together','打完交流思路'):t('Discuss picks before playing','选人前沟通'),must:false,visibility:'private',paused:false}))]);setSelected([]);setMemory(false);}}>{t('Add selected to draft','加入草稿')}</button></div>}</>}
  {error&&<p role="alert">{error}</p>}
  <button className="bp-primary" onClick={()=>{const err=validate();if(err){setError(err);return;}if(preview)onSave(draft);else setPreview(true);}}>{preview?t('Save and update','保存并更新'):t('Preview card','预览卡片')}</button>
  <button className="bp-text-button" onClick={()=>preview?setPreview(false):onCancel()}>{preview?t('Continue editing','继续编辑'):t('Cancel','取消')}</button>
 </div>;
}
